### ISSUE TITLE
Rename darkfish theme?

### ISSUE THREAD

**Issue by p8** [ruby/rdoc#1167]
With the new changes the default theme no longer resembles the original Darkfish.
Should this theme be renamed to something else?

This would also make it possible to remove the [footer link](https://github.com/ruby/rdoc/blob/master/lib/rdoc/generator/template/darkfish/_footer.rhtml#L4) to a page that no longer exists.
We could link to this repo instead.

**Comment by st0012** [comment]
Darkfish is the name of the [generator](https://github.com/ruby/rdoc/blob/master/lib/rdoc/generator/darkfish.rb), which includes the theme. And since the theme's file structure and the generator class are still largely the same, it's more like we're just using an updated version of darkfish.

I think practically speaking we may want to replace Darkfish altogether (but still keep it as an option) instead of doing a big enough update that requires a rename.
