### ISSUE TITLE
Formatting of `+<<+` is inconsistent.

### ISSUE THREAD

**Issue by ioquatix** [ruby/rdoc#1230]
I could not get `+<<+` to format as monotype.

As in, I had to do this:

```
+read+, +write+, <tt><<</tt>, +flush+, +close+, +close_read+, +close_write+, and +closed?+.
```

Also, `<tt><<</tt>` looks equally bizarre.

Is it possible to just support backticks ala Markdown?

**Comment by jeremyevans** [comment]
As I understand it, the long term plan for rdoc is to encourage people to write documentation in markdown (https://st0012.dev/a-rdoc-maintainer-s-view-on-ruby-s-documentation#heading-2-move-away-from-rdoc-markup-language-to-markdown), and therefore, I'm not sure that rdoc markup improvements have high priority.  I'm not an rdoc maintainer, and cannot speak for the rdoc maintainers, but since you already have a workaround, I would guess the priority to implement this support is low.  I assume if a pull request implementing it was provided, it would be accepted, though.

**Comment by ioquatix** [comment]
Thanks for your feedback.
