### ISSUE TITLE
RDoc 6.0.4 and Ruby 2.4.x hides Instance Public methods

### ISSUE THREAD

**Issue by gmcgibbon** [ruby/rdoc#665]
I was investigating a documentation issue on rails (https://github.com/rails/rails/issues/34396) and noticed that RDoc 6.0.4 hides the `Instance Public methods` section for [some of our docs](https://api.rubyonrails.org/v5.2/classes/ActionDispatch/Http/URL.html) when generating with Ruby 2.4.x. Docs generate normally when using Ruby 2.5.x.

Also, this seems to be fixed when generating rails docs with `v6.1.0.beta2` on Ruby 2.4.x, so I think its exclusively an issue with RDoc 6.0.4.

**Comment by sriedel** [comment]
@gmcgibbon : Are you an rvm user by any chance and built the docs using "rvm docs"? 
I've recently encountered the same issue with ruby 2.6.3 and rdoc 6.1.1 when building the docs via "rvm docs generate". Generating with plain rdoc --ri results in the correct method visibilities, so the issue may be due to something on the rvm side.

**Comment by gmcgibbon** [comment]
> Are you an rvm user by any chance and built the docs using "rvm docs"?

No, I'm using chruby. This is reproducible locally by checking out `5-2-stable` on rails and [invoking this `rdoc` task](https://github.com/rails/rails/blob/1aa90ddc1c2ae5d44f64f41c6eda3345054d69c2/Rakefile#L46-L51) using `ruby 2.4.6` and `rdoc 6.0.4`.

I just tried again with the now released `rdoc 6.1.1` and it works as expected. As such, I think this can be closed. @sriedel if you can get to the bottom of your problem, I would recommend opening up a separate issue.
