### ISSUE TITLE
:method:  seems to generate wrong line no.

### ISSUE THREAD

**Issue by neko314** [ruby/rdoc#750]
## Steps to reproduce
```ruby
# sample.rb

1 class Sample
2
3  # :method: hoege
4
5 end
```
Run `rdoc` and open generated file .

![image](https://user-images.githubusercontent.com/29836309/69589629-17ae6080-1030-11ea-833b-36070712232b.png)

## Expected behavior

The documentation says line no is 5, but I think it's better 3.

**Comment by aycabta** [comment]
Good catch, thank you for reporting! This is an important point to detect the definition position because I'll add a showing source code feature to IRB later. Please feel free to report other bugs or strange behaviors more too.

**Comment by neko314** [comment]
Thank you for fixing it!
I’ll report when I find anything wrong. Actually... I want to make PR in that case, so I'll try.
Anyway,  thanks so much.

**Comment by aycabta** [comment]
Maybe I need full-time 1 week to fix this problem if it's before I became the RDoc maintainer. It's too difficult because it's a core problem of Ruby's parser. I hope you to get new technical powers and confidence but I guessed this isn't a good problem to gein confidence for you or all new contributors. Therefore, I fixed this issue on a priority basis.

Let you try to find new challenges and try to fix. I welcome your adventure.
